services:
  klipper:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: klipper
    restart: unless-stopped
    privileged: true
    volumes:
      - ./moonraker_data/config:/home/moonraker/printer_data/config
      - ${GCODE_PATH:-./gcode}:/home/moonraker/printer_data/gcodes
      - ${SOCKETS_PATH:-./sockets}:/tmp
      - /dev/serial:/dev/serial
    environment:
      TZ: ${TZ:-UTC}
    logging:
      driver: local

  moonraker:
    build:
      context: .
      dockerfile: Dockerfile.moonraker
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        MOONRAKER_VERSION: ${MOONRAKER_VERSION:-master}
    container_name: moonraker
    restart: unless-stopped
    volumes:
      - ${MOONRAKER_DATA_PATH:-./moonraker_data}:/home/moonraker/printer_data
      - ${GCODE_PATH:-./gcode}:/home/moonraker/printer_data/gcodes
      - ${SOCKETS_PATH:-./sockets}:/tmp
      - ./config:/opt/klipper/config:ro
      - ./docs:/opt/klipper/docs:ro
    ports:
      - "7125:7125"
    environment:
      TZ: ${TZ:-UTC}
    depends_on:
      klipper:
        condition: service_started
    logging:
      driver: local

  fluidd:
    build:
      context: .
      dockerfile: Dockerfile.fluidd
      args:
        FLUIDD_VERSION: ${FLUIDD_VERSION:-master}
    container_name: fluidd
    restart: unless-stopped
    environment:
      TZ: ${TZ:-UTC}
    depends_on:
      moonraker:
        condition: service_started
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik"
      traefik.http.routers.fluidd.entrypoints: "http"
      traefik.http.routers.fluidd.rule: "Host(`sv06`) || Host(`sv06.gelse.local`)"
      traefik.http.routers.fluidd.service: "fluidd"
      traefik.http.services.fluidd.loadbalancer.server.port: "80"
    networks:
      - default
      - traefik
    logging:
      driver: local

networks:
  traefik:
    external: true
